// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalksAPI.Data;

#nullable disable

namespace NZWalksAPI.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20230731082007_Seeding Data For Difficulties and Regions")]
    partial class SeedingDataForDifficultiesandRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalksAPI.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2dcb513-7247-4d75-b7db-03aade5ff1ef"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("6ac9da36-95e8-4bac-860a-87f1eaa6edb3"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("9e5f67ec-4619-4ba9-b445-d87fd17ed8d8"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalksAPI.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("27a6d24f-371e-4af4-a2f7-ab74d297b7f9"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.britannica.com%2Fplace%2FAuckland-New-Zealand&psig=AOvVaw2hpeRBm_qe0iCUd2BG8wRe&ust=1690877606356000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCJjly4rAuIADFQAAAAAdAAAAABAE"
                        },
                        new
                        {
                            Id = new Guid("f700ede5-f310-4bdd-8be6-911b81231e87"),
                            Code = "NTL",
                            Name = "Northland",
                            RegionImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.live-work.immigration.govt.nz%2Fchoose-new-zealand%2Fregions-cities%2Fnorthland&psig=AOvVaw2RORpAHaf0KRscqiTYkxKS&ust=1690877642707000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCLDY7ZvAuIADFQAAAAAdAAAAABAE"
                        },
                        new
                        {
                            Id = new Guid("2c9c5ca2-9b91-4e9f-b41d-ddf7da3f20fc"),
                            Code = "BOP",
                            Name = "Bay Of Plenty"
                        },
                        new
                        {
                            Id = new Guid("349b6d85-64be-4a73-ba9f-55c91cb471cf"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.britannica.com%2Fplace%2FWellington-New-Zealand&psig=AOvVaw11t71unddmgm6Gb9G_g-A1&ust=1690877729327000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCOjlnMXAuIADFQAAAAAdAAAAABAE"
                        },
                        new
                        {
                            Id = new Guid("c6c60f8f-a36a-4cac-b974-5d5d3e0b996f"),
                            Code = "MSN",
                            Name = "Nelson",
                            RegionImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FNelson%2C_New_Zealand&psig=AOvVaw3pcHu97yy98Fr_k1DNtsmZ&ust=1690877770505000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCOC-4NjAuIADFQAAAAAdAAAAABAE"
                        },
                        new
                        {
                            Id = new Guid("0bb7df90-bf33-49ba-8c0f-64c382aaf43a"),
                            Code = "STL",
                            Name = "Southland"
                        });
                });

            modelBuilder.Entity("NZWalksAPI.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalksAPI.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalksAPI.Models.Domain.Difficulty", "Diffculty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalksAPI.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diffculty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
